name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Build with Jekyll
        run: |
          jekyll build --config=_config.yml,_config_deploy.yml --no-scss --no-converter-scss --sass=none
      - name: Deploy to GitHub Pages
        uses: github-pages/deploy@v1
