name: Matatan Virtual Barista

on:
  push:
    branches: 
      - master
      - main
  pull_request:
    branches: 
      - master
      - main
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: false
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python 3.12.2
      uses: actions/setup-python@v2
      with:
        python-version: 3.12.2

    - name: Install Build Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake ninja-build gcc g++ libffi-dev
        if [ ! -f /usr/bin/cc ]; then sudo ln -s /usr/bin/gcc /usr/bin/cc; fi
        if [ ! -f /usr/bin/c++ ]; then sudo ln -s /usr/bin/g++ /usr/bin/c++; fi

    - name: Install Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install meson
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
  
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.0'

    - name: Install Flet
      run: |
        pip install flet

    - name: Flet Build Web
      run: |
        echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}, USER: ${GITHUB_REPOSITORY%/*}, PROJECT_BASE_URL: ${GITHUB_REPOSITORY#*/}"
        flet build web --base-url ${GITHUB_REPOSITORY#*/} --route-url-strategy hash

    - name: Upload Artifact
      uses: actions/upload-pages-artifact@v3
      with:
        name: web-build-artifact
        path: build/web

  deploy:
    needs: build

    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v5
        
      - name: Deploy to GitHub Pages 🚀
        if: github.event_name == 'push'
        id: deployment
        uses: actions/deploy-pages@v4.0.5
        with:
          artifact_name: web-build-artifact
